# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "battery" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b7dcb30c-e8a8-4450-8297-c5b81975fa6f";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/20ac52dd-b7ad-46a1-964f-2cd025dfb0e1";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b7dcb30c-e8a8-4450-8297-c5b81975fa6f";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b7dcb30c-e8a8-4450-8297-c5b81975fa6f";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/b7dcb30c-e8a8-4450-8297-c5b81975fa6f";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/b7dcb30c-e8a8-4450-8297-c5b81975fa6f";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/17AE-3D77";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7aaeef47-7f4d-4095-bae3-f63aa98a7075"; }
    ];

  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp82s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
  # compensate for thinkpad trackpoint name
  hardware.trackpoint.device = "TPPS/2 Elan TrackPoint";
  # get discrete HDMI port to work
  hardware.bumblebee.connectDisplay = true;
  nixpkgs.overlays = [
    (self: super: {
      bumblebee = super.bumblebee.override {
        extraNvidiaDeviceOptions = ''
          Option "AllowEmptyInitialConfiguration"
        '';
      };
    })
  ];

  # may not do anything on wayland but good reference if needed
  services.xserver = mkMerge [
    {
      # set the right DPI. xdpyinfo says the screen is 508x285 but it's actually 344x193
      monitorSection = ''
        DisplaySize 344 193
      '';
    }

    # to support intel-virtual-output when using Bumblebee
    (mkIf config.hardware.bumblebee.enable {
      deviceSection = ''Option "VirtualHeads" "1"'';
      videoDrivers = [ "intel" ];
    })
  ];

  services.throttled.enable = lib.mkDefault true;
}
